#!/usr/bin/env bash
# Lab 02, Step 2 — generate traffic, then read four independent evidence
# sources and decide which one produced the 503.
#
# Run this only after cli/01-create.sh has finished and after the target group
# health checks have run at least once (they poll every 15s).
#
set -euo pipefail

AWS_REGION="${AWS_REGION:-us-east-1}"
PREFIX="soa-c03-lab02"
REQUESTS="${REQUESTS:-5}"

if [[ -z "${AWS_PROFILE:-}" ]]; then
  echo "ERROR: set AWS_PROFILE to the authorized profile before running." >&2
  exit 1
fi

ALB_ARN="$(aws elbv2 describe-load-balancers --names "${PREFIX}-alb" \
  --query 'LoadBalancers[0].LoadBalancerArn' --output text)"
ALB_DNS="$(aws elbv2 describe-load-balancers --load-balancer-arns "$ALB_ARN" \
  --query 'LoadBalancers[0].DNSName' --output text)"
TG_ARN="$(aws elbv2 describe-target-groups --names "${PREFIX}-tg" \
  --query 'TargetGroups[0].TargetGroupArn' --output text)"

echo "== Target group health =="
aws elbv2 describe-target-health --target-group-arn "$TG_ARN" \
  --query 'TargetHealthDescriptions[].{Target:Target.Id,State:TargetHealth.State,Reason:TargetHealth.Reason,Description:TargetHealth.Description}' \
  --output table

echo
echo "== Sending $REQUESTS requests to http://$ALB_DNS/ =="
for i in $(seq 1 "$REQUESTS"); do
  curl -s -o /dev/null -D - --max-time 10 "http://${ALB_DNS}/" \
    | awk 'BEGIN{IGNORECASE=1} /^HTTP\/|^server:|^x-amzn-requestid:|^x-amzn-trace-id:/ {printf "  %s", $0} END{print ""}' \
    | tr -d '\r'
  sleep 1
done

NOW="$(date -u '+%Y-%m-%dT%H:%M:%SZ')"
START="$(($(date -u +%s) - 1800))"   # epoch seconds; accepted by CloudWatch
NOW_EPOCH="$(date -u +%s)"

echo
echo "== Which 5xx metric moved? =="
echo "   HTTPCode_ELB_5XX_Count    generated by the load balancer"
echo "   HTTPCode_Target_5XX_Count generated by a target"
for m in HTTPCode_ELB_5XX_Count HTTPCode_Target_5XX_Count; do
  printf '  %-28s ' "$m"
  aws cloudwatch get-metric-statistics \
    --namespace AWS/ApplicationELB --metric-name "$m" \
    --dimensions Name=LoadBalancer,Value="${ALB_ARN#*:loadbalancer/}" \
    --start-time "$START" --end-time "$NOW" \
    --period 300 --statistics Sum \
    --query 'Datapoints[?SampleCount>`0`].{t:Timestamp,Sum:Sum}' --output table 2>/dev/null \
    || echo "(no datapoints)"
done

echo
echo "== ALB access logs (S3) =="
LOG_BUCKET="$(aws elbv2 describe-load-balancer-attributes --load-balancer-arn "$ALB_ARN" \
  --query 'Attributes[?Key==`access_logs.s3.bucket`].Value | [0]' --output text)"
if [[ "$LOG_BUCKET" == "None" || -z "$LOG_BUCKET" ]]; then
  echo "  access logs are not enabled; re-run 01-create.sh"
else
  echo "  bucket: $LOG_BUCKET"
  echo "  listing newest objects:"
  aws s3 ls "s3://${LOG_BUCKET}/AWSLogs/" --recursive --region "$AWS_REGION" 2>/dev/null | tail -5 || true
  echo
  echo "  Confirm ELBAccessLogTestFile exists, then wait ~5 minutes for real log files."
  echo "  Download one and read: timestamp, elb_status, target_status, target_group_arn."
  echo "  elb_status=503 with target_status=503? No — target_status is 0 here, which"
  echo "  means no target ever ran and the fixed response was served."
fi

echo
echo "== VPC Flow Logs (CloudWatch Logs Insights) =="
aws logs start-query \
  --log-group-name "/aws/vpc/flowlogs/${PREFIX}" \
  --start-time "$START" \
  --end-time "$NOW_EPOCH" \
  --query-string 'fields @timestamp, srcaddr, dstaddr, dstport, protocol, action | filter action = "REJECT" or dstport = 80 | sort @timestamp desc | limit 20' \
  --query queryId --output text

cat <<'EOF'

  A Flow Log record tells you the flow existed and what the NACL layer decided.
  It does not carry HTTP status, headers, target group, or application errors.
  If nothing is listed, that is a statement about the log, not about reachability.
EOF
