#!/usr/bin/env bash
# Lab 04 shared helpers — sourced by the numbered scripts, never executed.
#
# Two jobs:
#   1. Remember one run's identifiers so every script agrees on them. The run
#      file is `cli/.env.lab04-run`, which the repository .gitignore already
#      covers with its `.env.*` rule. It holds the lab master password, so
#      never commit it and never paste it anywhere.
#   2. Poll AWS for state changes with a visible timeout instead of sleeping
#      and assuming.
#
# bash 3.2 compatible: no mapfile, no arrays, no ${var^^}. Verified on the
# macOS system bash.
#
# Waiters: this CLI has rds wait db-instance-available, db-instance-deleted,
# db-snapshot-available, db-snapshot-completed and db-snapshot-deleted
# (`aws rds wait help`). Each caps out at 40 attempts x 15s, roughly ten
# minutes, which a restore can exceed. lab_wait_instance/lab_wait_snapshot
# below are explicit polling loops so the timeout is visible and the exit
# status is meaningful; teardown uses db-instance-deleted where the wait is
# short and bounded.

LAB_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
RUN_FILE="${LAB_RUN_FILE:-$LAB_DIR/.env.lab04-run}"

lab_die() {
  echo "ERROR: $*" >&2
  exit 1
}

lab_need_profile() {
  [[ -n "${AWS_PROFILE:-}" ]] || lab_die "set AWS_PROFILE to the authorized profile first"
  [[ -n "${AWS_REGION:-}" ]] || export AWS_REGION="us-east-1"
}

lab_need_cmd() {
  command -v "$1" >/dev/null 2>&1 || lab_die "'$1' is required but not installed"
}

lab_utc_now() { date -u +%Y-%m-%dT%H:%M:%SZ; }
lab_epoch() { date -u +%s; }

# ISO 8601 UTC from an epoch value. Tries BSD date, then GNU date, then python3.
lab_iso_from_epoch() {
  local e="$1" out=""
  out="$(date -u -r "$e" +%Y-%m-%dT%H:%M:%SZ 2>/dev/null || true)"
  [[ -n "$out" ]] || out="$(date -u -d "@$e" +%Y-%m-%dT%H:%M:%SZ 2>/dev/null || true)"
  [[ -n "$out" ]] || out="$(python3 -c 'import sys,time;print(time.strftime("%Y-%m-%dT%H:%M:%SZ",time.gmtime(int(sys.argv[1]))))' "$e" 2>/dev/null || true)"
  [[ -n "$out" ]] || lab_die "could not convert epoch $e to a timestamp"
  printf '%s\n' "$out"
}

# Epoch from an AWS ISO timestamp such as 2026-10-03T18:42:03.123456Z.
lab_epoch_from_iso() {
  local iso="$1" clean out=""
  [[ -n "$iso" ]] || return 1
  clean="$(printf '%s' "$iso" | sed 's/\.[0-9]*Z*$//; s/Z$//; s/+00:00$//')"
  out="$(date -u -j -f '%Y-%m-%dT%H:%M:%S' "$clean" +%s 2>/dev/null || true)"
  [[ -n "$out" ]] || out="$(date -u -d "$clean UTC" +%s 2>/dev/null || true)"
  [[ -n "$out" ]] || out="$(python3 -c 'import sys,calendar,time;print(calendar.timegm(time.strptime(sys.argv[1],"%Y-%m-%dT%H:%M:%S")))' "$clean" 2>/dev/null || true)"
  [[ -n "$out" ]] || return 1
  printf '%s\n' "$out"
}

lab_hhmm() {
  local m=$(( $1 % 1440 ))
  printf '%02d:%02d' $(( m / 60 )) $(( m % 60 ))
}

# Print "<day> <backup_window> <maintenance_window>" for an RDS instance.
# Both windows are 30 minutes, are in UTC, and must not overlap or cross
# midnight, so they are derived from one lead time. Override with
# BACKUP_WINDOW / MAINTENANCE_WINDOW if AWS rejects them for an account-specific
# reason; the override values are echoed back so the record shows what ran.
lab_compute_windows() {
  local now lead b day
  now="$(lab_epoch)"
  lead="${LAB_BACKUP_LEAD_SECONDS:-900}"
  b=$(( (now + lead) / 300 * 300 ))
  while [[ $(( b - now )) -lt 600 ]]; do b=$(( b + 300 )); done
  day="$(date -u +%a)"
  if [[ -n "${BACKUP_WINDOW:-}" && -n "${MAINTENANCE_WINDOW:-}" ]]; then
    printf '%s %s %s\n' "$day" "$BACKUP_WINDOW" "$MAINTENANCE_WINDOW"
    return 0
  fi
  if [[ $(( (b + 65) / 1440 )) -ne $(( b / 1440 )) ]]; then
    # The derived windows would cross midnight UTC, which RDS does not accept.
    b=$(( (now / 1440 ) * 1440 + 10800 ))   # today 03:00 UTC
    if [[ $(( b - now )) -lt 1800 ]]; then
      b=$(( b + 86400 ))
      echo "  NOTE: no room for a 30-minute backup window before midnight UTC." >&2
      echo "        Using tomorrow's window, so the first automated backup will" >&2
      echo "        NOT run during this session. Steps 07 will report that." >&2
    else
      echo "  NOTE: using the fixed 03:00 UTC window; the derived one crossed midnight." >&2
    fi
  fi
  printf '%s %s %s-%s\n' "$day" \
    "$(lab_hhmm "$b")-$(lab_hhmm $(( b + 1800 )))" \
    "$(lab_hhmm $(( b + 2100 )))" \
    "$(lab_hhmm $(( b + 3900 )))"
}

# ---------------------------------------------------------------- run file
lab_load() {
  [[ -f "$RUN_FILE" ]] || lab_die "no run file at $RUN_FILE — run cli/01-create.sh first"
  # shellcheck disable=SC1090
  . "$RUN_FILE"
  : "${LAB_REGION:?run file is missing LAB_REGION}"
  : "${LAB_DB_PASSWORD:?run file is missing LAB_DB_PASSWORD}"
}

lab_save() {
  local tmp
  tmp="$(mktemp "${TMPDIR:-/tmp}/lab04run.XXXXXX")"
  {
    printf '# Generated by lab 04. Contains the lab master password.\n'
    printf '# Covered by the repository .gitignore rule .env.* — never commit it.\n'
    local k
    for k in LAB_RUN_SUFFIX LAB_REGION LAB_DR_REGION LAB_DB_USER LAB_DB_PASSWORD \
             LAB_DB_NAME LAB_SG LAB_PRIMARY LAB_PRIMARY_ENDPOINT LAB_PRIMARY_PORT \
             LAB_BACKUP_WINDOW LAB_MAINTENANCE_WINDOW LAB_BACKUP_DAY \
             LAB_SEED_ROWS LAB_SEED_SUM LAB_SEED_FIRST5 LAB_SEED_NEWEST_GOOD LAB_SEED_EPOCH \
             LAB_SNAPSHOT LAB_SNAPSHOT_TIME LAB_SNAPSHOT_EPOCH \
             LAB_BAD_WRITE_EPOCH LAB_BAD_WRITE_TIME \
             LAB_RESTORED LAB_RESTORE_TARGET_LABEL \
             LAB_RESTORE_REQUEST_EPOCH LAB_RESTORE_AVAILABLE_EPOCH \
             LAB_RESTORE_SQL_EPOCH LAB_RESTORE_ELAPSED_AVAILABLE LAB_RESTORE_ELAPSED_SQL \
             LAB_PITR LAB_PITR_TARGET_TIME LAB_PITR_TARGET_EPOCH \
             LAB_PITR_REQUEST_EPOCH LAB_PITR_AVAILABLE_EPOCH \
             LAB_PITR_SQL_EPOCH LAB_PITR_ELAPSED_AVAILABLE LAB_PITR_ELAPSED_SQL \
             LAB_REPLICA LAB_DR_SG LAB_DR_REPLICA_ENDPOINT \
             LAB_LAG_MARKER_ID LAB_LAG_WROTE_EPOCH LAB_LAG_SEEN_EPOCH LAB_LAG_SECONDS; do
      printf '%s=%s\n' "$k" "${!k:-}"
    done
  } > "$tmp"
  chmod 600 "$tmp"
  mv "$tmp" "$RUN_FILE"
  echo "  run state: $RUN_FILE (gitignored, mode 600)"
}

lab_require_run() {
  [[ -f "$RUN_FILE" ]] || lab_die "no run file at $RUN_FILE — run cli/01-create.sh first"
}

# ------------------------------------------------------------------ naming
lab_new_suffix() {
  printf '%s-%s\n' "$(date -u +%m%d%H%M%S)" "$RANDOM"
}

lab_names() {
  : "${LAB_RUN_SUFFIX:?}"
  LAB_SG="soa-c03-lab04-sg-${LAB_RUN_SUFFIX}"
  LAB_DR_SG="soa-c03-lab04-sg-${LAB_RUN_SUFFIX}"
  LAB_PRIMARY="soa-c03-lab04-primary-${LAB_RUN_SUFFIX}"
  LAB_SNAPSHOT="soa-c03-lab04-snap-${LAB_RUN_SUFFIX}"
  LAB_RESTORED="soa-c03-lab04-restored-${LAB_RUN_SUFFIX}"
  LAB_PITR="soa-c03-lab04-pitr-${LAB_RUN_SUFFIX}"
  LAB_REPLICA="soa-c03-lab04-replica-${LAB_RUN_SUFFIX}"
  LAB_TAG_KEY="soa-c03-lab04"
  LAB_TAG_VALUE="$LAB_RUN_SUFFIX"
  export LAB_SG LAB_DR_SG LAB_PRIMARY LAB_SNAPSHOT LAB_RESTORED LAB_PITR LAB_REPLICA
  export LAB_TAG_KEY LAB_TAG_VALUE
}

lab_public_ip() {
  if [[ -n "${PUBLIC_IP:-}" ]]; then
    printf '%s\n' "$PUBLIC_IP"
    return 0
  fi
  curl -fsS --max-time 10 https://checkip.amazonaws.com 2>/dev/null \
    || lab_die "could not determine this machine's public IP; re-run with PUBLIC_IP=x.x.x.x/32"
}

# ------------------------------------------------------------------ waiting
lab_instance_status() {
  aws rds describe-db-instances --db-instance-identifier "$1" \
    --query 'DBInstances[0].DBInstanceStatus' --output text 2>/dev/null || echo unknown
}

lab_snapshot_status() {
  aws rds describe-db-snapshots --db-snapshot-identifier "$1" \
    --query 'DBSnapshots[0].Status' --output text 2>/dev/null || echo unknown
}

# One scalar member at a time. `--output text` on a multi-key projection prints
# values in an order that is not worth relying on, and this lab must not depend
# on that.
lab_snap_field() {
  aws rds describe-db-snapshots --db-snapshot-identifier "$1" \
    --query "DBSnapshots[0].$2" --output text 2>/dev/null || echo None
}

lab_instance_field() {
  aws rds describe-db-instances --db-instance-identifier "$1" \
    --query "DBInstances[0].$2" --output text 2>/dev/null || echo None
}

# Poll until an instance reports `available`. Prints every status transition and
# exits non-zero on timeout, so a half-finished restore is never mistaken for a
# finished one.
lab_wait_instance() {
  local id="$1" label="$2" timeout="${3:-2400}"
  local start now elapsed last="" status
  start="$(lab_epoch)"
  echo "  waiting for $label ($id) to report available; timeout ${timeout}s"
  while :; do
    now="$(lab_epoch)"
    elapsed=$(( now - start ))
    status="$(lab_instance_status "$id")"
    if [[ "$status" != "$last" ]]; then
      printf '    [%4ss] %s: %s\n' "$elapsed" "$label" "$status"
      last="$status"
    fi
    [[ "$status" == "available" ]] && return 0
    if [[ $(( elapsed )) -ge $(( timeout )) ]]; then
      printf '    [%4ss] TIMEOUT: %s is %s, not available\n' "$elapsed" "$label" "$status" >&2
      echo "    Inspect before deleting: aws rds describe-db-instances --db-instance-identifier $id" >&2
      return 1
    fi
    sleep 15
  done
}

lab_wait_snapshot() {
  local id="$1" label="$2" timeout="${3:-1800}"
  local start now elapsed last="" status
  start="$(lab_epoch)"
  echo "  waiting for $label ($id) to finish; timeout ${timeout}s"
  while :; do
    now="$(lab_epoch)"
    elapsed=$(( now - start ))
    status="$(lab_snapshot_status "$id")"
    if [[ "$status" != "$last" ]]; then
      printf '    [%4ss] %s: %s\n' "$elapsed" "$label" "$status"
      last="$status"
    fi
    case "$status" in
      available|completed) return 0 ;;
    esac
    if [[ $(( elapsed )) -ge $(( timeout )) ]]; then
      printf '    [%4ss] TIMEOUT: %s is %s\n' "$elapsed" "$label" "$status" >&2
      return 1
    fi
    sleep 15
  done
}

# Poll until the instance answers a trivial SQL query. "available" is a
# control-plane statement; answering a query is the usability statement, and the
# RTO is only met at the second one.
lab_wait_sql() {
  local host="$1" port="$2" label="$3" timeout="${4:-900}"
  local start now elapsed
  start="$(lab_epoch)"
  echo "  waiting for $label to answer a query; timeout ${timeout}s"
  while :; do
    now="$(lab_epoch)"
    elapsed=$(( now - start ))
    if lab_sql "$host" "$port" "SELECT 1;" >/dev/null 2>&1; then
      printf '    [%4ss] %s answered a query\n' "$elapsed" "$label"
      return 0
    fi
    if [[ $(( elapsed )) -ge $(( timeout )) ]]; then
      printf '    [%4ss] TIMEOUT: %s never answered a query\n' "$elapsed" "$label" >&2
      echo "    The instance may still be starting, or the security group may not" >&2
      echo "    allow this machine. Both are findings — record which one." >&2
      return 1
    fi
    sleep 10
  done
}

# ------------------------------------------------------------------- SQL
# Runs one SQL string and prints bare pipe-separated values. Needs psql, or
# docker so the official postgres image can supply psql.
lab_sql() {
  local host="$1" port="$2" sql="$3"
  : "${LAB_DB_PASSWORD:?}"
  if command -v psql >/dev/null 2>&1; then
    PGPASSWORD="$LAB_DB_PASSWORD" PGOPTIONS='-c timezone=UTC' \
      psql -X -q -t -A -F '|' -v ON_ERROR_STOP=1 \
        -h "$host" -p "$port" -U "$LAB_DB_USER" -d "$LAB_DB_NAME" -c "$sql"
  elif command -v docker >/dev/null 2>&1; then
    docker run --rm -e PGPASSWORD -e 'PGOPTIONS=-c timezone=UTC' \
      "${LAB_PG_IMAGE:-postgres:17-alpine}" \
      psql -X -q -t -A -F '|' -v ON_ERROR_STOP=1 \
        -h "$host" -p "$port" -U "$LAB_DB_USER" -d "$LAB_DB_NAME" -c "$sql"
  else
    lab_die "need psql (brew install libpq) or docker to run SQL"
  fi
}

# ------------------------------------------------------------- verification
# The canary query. Counts, a checksum, the newest good row and the first five
# rows together answer "is this the copy I think it is, and how fresh is it".
lab_verify_data() {
  local host="$1" port="$2" expect_good="$3" expect_poison="$4" \
        expect_first5="$5" expect_checksum="$6" expect_newest="$7"
  local row good poison newest checksum first5 total
  row="$(lab_sql "$host" "$port" "
SELECT (count(*) FILTER (WHERE kind = 'good'))::bigint,
       (count(*) FILTER (WHERE kind = 'poison'))::bigint,
       to_char(max(written_at) FILTER (WHERE kind = 'good'), 'YYYY-MM-DD HH24:MI:SS'),
       sum(payload) FILTER (WHERE kind = 'good'),
       (count(*) FILTER (WHERE kind = 'good' AND id <= 5))::bigint,
       count(*)::bigint
FROM public.lab04_events;")"
  IFS='|' read -r good poison newest checksum first5 total <<< "$row"
  [[ -n "${good:-}" ]] || lab_die "verification query returned nothing: $row"

  echo "  canary query against $host:$port"
  printf '    %-34s %-24s %s\n' "good rows" "$good" "expected $expect_good"
  printf '    %-34s %-24s %s\n' "poison rows" "$poison" "expected $expect_poison"
  printf '    %-34s %-24s %s\n' "checksum(sum payload)" "$checksum" "expected $expect_checksum"
  printf '    %-34s %-24s %s\n' "rows 1-5 still present" "$first5" "expected $expect_first5"
  printf '    %-34s %-24s %s\n' "newest good row" "$newest" "expected ${expect_newest:-any}"
  printf '    %-34s %-24s\n' "total rows" "$total"

  local failed=0
  cmp_num() {
    if [[ "$2" == "$3" ]]; then
      printf '    PASS %s = %s\n' "$1" "$2"
    else
      printf '    FAIL %s = %s (expected %s)\n' "$1" "$2" "$3"
      failed=1
    fi
  }
  cmp_num "good rows" "$good" "$expect_good"
  cmp_num "poison rows" "$poison" "$expect_poison"
  cmp_num "checksum" "$checksum" "$expect_checksum"
  cmp_num "rows 1-5" "$first5" "$expect_first5"
  if [[ -n "${expect_newest:-}" && "$newest" != "$expect_newest" ]]; then
    printf '    INFO newest good row is %s; the run recorded %s (a few seconds of\n' "$newest" "$expect_newest"
    printf '         write drift is normal, an empty value is not)\n'
  fi
  if [[ "$failed" -eq 0 ]]; then
    echo "    VERDICT: this copy matches what was claimed. The restore is proven."
  else
    echo "    VERDICT: this copy does NOT match the claim. Do not call it recovered."
  fi
  return "$failed"
}
